[package]
name = "raylib-wasm"
version = "0.0.17"
authors = ["Mark Tyrkba <marktyrkba456@gmail.com>"]
license = "MIT"
description = "raylib native/wasm bindings"
repository = "https://github.com/rakivo/raylib-light"
keywords = ["bindings", "raylib", "gamedev", "web", "wasm"]
categories = ["api-bindings", "game-engines", "graphics"]
edition = "2021"

[package.metadata]
include = ["raylib.js"]

[features]
web = []
native = []

[lib]
crate-type = ["rlib"]
path = "raylib.rs"